package edu.playground.djivln.logging

import edu.playground.djivln.domain.telemetry.AircraftSnapshot

object FlightTelemetryLogPayload {
    fun fields(snapshot: AircraftSnapshot): Map<String, Any?> = mapOf(
        "connected" to snapshot.connected,
        "simulator" to snapshot.simulatorActive,
        "flying" to snapshot.isFlying,
        "motors_on" to snapshot.motorsOn,
        "flight_mode" to snapshot.flightMode,
        "go_home_state" to snapshot.goHomeState,
        "go_home_confirm_type" to snapshot.goHomeConfirmType,
        "auto_rth_reason" to snapshot.autoRthReason,
        "failsafe_active" to snapshot.failsafeActive,
        "failsafe_action" to snapshot.failsafeAction,
        "low_battery_rth_enabled" to snapshot.lowBatteryRthEnabled,
        "low_battery_rth_state" to snapshot.lowBatteryRthState,
        "smart_rth_countdown_s" to snapshot.smartRthCountdownSeconds,
        "remaining_flight_time_s" to snapshot.remainingFlightTimeSeconds,
        "time_needed_go_home_s" to snapshot.timeNeededToGoHomeSeconds,
        "time_needed_land_s" to snapshot.timeNeededToLandSeconds,
        "battery_needed_go_home_pct" to snapshot.batteryNeededToGoHomePercent,
        "battery_needed_land_pct" to snapshot.batteryNeededToLandPercent,
        "max_safe_radius_m" to snapshot.maxSafeFlightRadiusMeters,
        "latitude" to snapshot.aircraftLocation?.latitude,
        "longitude" to snapshot.aircraftLocation?.longitude,
        "altitude_m" to snapshot.relativeAltitudeMeters,
        "velocity_north_mps" to snapshot.velocity?.north,
        "velocity_east_mps" to snapshot.velocity?.east,
        "velocity_up_mps" to snapshot.velocity?.up,
        "aircraft_roll_deg" to snapshot.attitude?.roll,
        "aircraft_pitch_deg" to snapshot.attitude?.pitch,
        "aircraft_yaw_deg" to snapshot.attitude?.yaw,
        "heading_deg" to snapshot.headingDegrees,
        "gimbal_pitch_deg" to snapshot.gimbalPitchDegrees,
        "aircraft_battery_pct" to snapshot.aircraftBatteryPercent,
        "rc_battery_pct" to snapshot.remoteControllerBatteryPercent,
        "rc_signal_pct" to snapshot.remoteControllerSignalPercent,
        "stick_left_horizontal" to snapshot.leftStickHorizontal,
        "stick_left_vertical" to snapshot.leftStickVertical,
        "stick_right_horizontal" to snapshot.rightStickHorizontal,
        "stick_right_vertical" to snapshot.rightStickVertical,
        "stick_max_abs" to maxOf(
            kotlin.math.abs(snapshot.leftStickHorizontal),
            kotlin.math.abs(snapshot.leftStickVertical),
            kotlin.math.abs(snapshot.rightStickHorizontal),
            kotlin.math.abs(snapshot.rightStickVertical),
        ),
        "gps_satellites" to snapshot.gpsSatelliteCount,
        "gps_signal" to snapshot.gpsSignalLevel,
        "go_home_height_m" to snapshot.goHomeHeightMeters,
        "max_height_m" to snapshot.maxFlightHeightMeters,
        "max_radius_m" to snapshot.maxFlightRadiusMeters,
        "max_radius_enabled" to snapshot.maxFlightRadiusEnabled,
        "sticks_active" to snapshot.sticksActive,
    )

    fun transitionSignature(snapshot: AircraftSnapshot): String = listOf(
        snapshot.connected,
        snapshot.simulatorActive,
        snapshot.isFlying,
        snapshot.motorsOn,
        snapshot.flightMode,
        snapshot.goHomeState,
        snapshot.goHomeConfirmType,
        snapshot.autoRthReason,
        snapshot.failsafeActive,
        snapshot.failsafeAction,
        snapshot.lowBatteryRthEnabled,
        snapshot.lowBatteryRthState,
        snapshot.smartRthCountdownSeconds,
        snapshot.sticksActive,
    ).joinToString("|")
}
