org.gradle.daemon=true
org.gradle.parallel=true
org.gradle.configureondemand=true
org.gradle.jvmargs=-Xmx4608M -Dfile.encoding=UTF-8

android.useAndroidX=true
android.enableJetifier=true
android.nonTransitiveRClass=false
android.disableResourceValidation=true

ANDROID_MIN_SDK_VERSION=24
ANDROID_TARGET_SDK_VERSION=35
ANDROID_COMPILE_SDK_VERSION=35
KOTLIN_VERSION=2.1.0

AIRCRAFT_API_KEY=Please add your DJI app key here.
